[Icon Theme]
Name=FilzaOS
Comment=FilzaOS Purple Icon Theme
Inherits=Yaru-purple,Yaru,Adwaita,hicolor
Directories=scalable/places,scalable/mimetypes,scalable/status,scalable/actions,scalable/apps,symbolic/places,symbolic/mimetypes,symbolic/status,symbolic/actions,symbolic/apps

[scalable/places]
Context=Places
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/mimetypes]
Context=MimeTypes
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/status]
Context=Status
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/actions]
Context=Actions
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[scalable/apps]
Context=Applications
Size=48
Type=Scalable
MinSize=16
MaxSize=512

[symbolic/places]
Context=Places
Size=16
Type=Scalable
MinSize=16
MaxSize=512

[symbolic/mimetypes]
Context=MimeTypes
Size=16
Type=Scalable
MinSize=16
MaxSize=512

[symbolic/status]
Context=Status
Size=16
Type=Scalable
MinSize=16
MaxSize=512

[symbolic/actions]
Context=Actions
Size=16
Type=Scalable
MinSize=16
MaxSize=512

[symbolic/apps]
Context=Applications
Size=16
Type=Scalable
MinSize=16
MaxSize=512
